version: "3.5"
services:

  web:
    build: web
    expose:
      - 80
    ports:
      - "8086:80"
    networks:
      - "backend"
    depends_on:
      - postgres

  postgres:
    build: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - "backend"

networks:
  backend:
    name: backend
